bump linter version
Repair linter bug caused by newer version of ansible.

ImportError: cannot import name module_loader

See https://github.com/willthames/ansible-lint/issues/278

Change-Id: I795f61c68de3122fc2c9b52a58da36a1d784e884