Update patch set 1
Patch Set 1:

because rhelosp-16.0-trunk-brew is not a valid name anymore

Failed to download metadata for repo 'rhelosp-16.0-trunk-brew'
Error: Failed to download metadata for repo 'rhelosp-16.0-trunk-brew'

Patch-set: 1
Reviewer: Gerrit User 1004788 <1004788@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1016110 <1016110@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1016991 <1016991@d5d70762-12d0-45a1-890d-524b12d3f735>
Reviewer: Gerrit User 1009116 <1009116@d5d70762-12d0-45a1-890d-524b12d3f735>