Update patch set 4
Abandoned

THT tests require Python3:
____________________________________
ERROR:   pep8: InterpreterNotFound: python3

Patch-set: 4
Status: abandoned
Tag: autogenerated:gerrit:abandon