[cinder][16.1][16.2][functional] Fix Errno 13 on cinder.egg removal
tox tries to install dependances in .
Therefore there is no need to install them beforehand.
Moreover, installing dependances with sudo results in the following error:

    Found existing installation: cinder 15.3.1.dev58
...
  Running setup.py develop for cinder
    ERROR: Command errored out with exit status 1:
    Complete output (3 lines):
    running develop
    running egg_info
    error: [Errno 13] Permission denied

Change-Id: Ie255de355d9532fdcef3377489a1d2961ed120af