Update patch set 2
Patch Set 2:

> Was it verified? Can we merge?

It looks good with a pep8 run, job ran up to:
pep8 run-test: commands[1] | flake8
[19002] /home/cloud-user/openstack-tempest$ /usr/local/bin/flake8
  unknown option 'import-order-style' ignored
/usr/lib/python3.6/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
./tempest/common/utils/linux/remote_client.py:61:13: E741 ambiguous variable name 'l'
        for l in output.splitlines():
            ^
./tempest/common/utils/linux/remote_client.py:114:34: E741 ambiguous variable name 'l'
        entries = (l.split() for l in resolve_file)
                                 ^
./tempest/common/utils/linux/remote_client.py:115:33: E741 ambiguous variable name 'l'
        dns_servers = [l[1] for l in entries
                                ^
ERROR: InvocationError for command /usr/local/bin/flake8 (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed

So tox itself ran fine

I am running a UT job in parallel to check that one also

Patch-set: 2