[cinder][16.1][16.2][functional] Fix Errno 13 on cinder.egg removal
tox tries to install dependances in .
Therefore there is no need to install them beforehand.
Moreover, installing dependances with sudo results in the following error:

    Found existing installation: cinder 15.3.1.dev58
    Not uninstalling cinder at /home/cloud-user/cinder, outside environment /home/cloud-user/cinder/.tox/functional-py36
    Can't uninstall 'cinder'. No files were found to uninstall.
  Running setup.py develop for cinder
    ERROR: Command errored out with exit status 1:
     command: /home/cloud-user/cinder/.tox/functional-py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/cloud-user/cinder/setup.py'"'"'; __file__='"'"'/home/cloud-user/cinder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/cloud-user/cinder/
    Complete output (3 lines):
    running develop
    running egg_info
    error: [Errno 13] Permission denied

Change-Id: Ie255de355d9532fdcef3377489a1d2961ed120af