[glance_store][16.2] Use sitepackages for pep8 tests
To fix pip and rpm packages conflicts.

Error message:
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/cloud-user/glance_store/.tox/pep8/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mdttsq6r/suds-jurko_3632c5bf1f114b77b4844bde635d03d2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mdttsq6r/suds-jurko_3632c5bf1f114b77b4844bde635d03d2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lbde_3i1
       cwd: /tmp/pip-install-mdttsq6r/suds-jurko_3632c5bf1f114b77b4844bde635d03d2/
  Complete output (1 lines):
  error in suds-jurko setup command: use_2to3 is invalid.

OSPCRE-85

Change-Id: Icb4cabc66825491696e2303c83eeee8d87a556e8